#include "nengine/scripting/managed_project.hpp"
#include "nengine/scripting/dotnet_host.hpp"

#include <fstream>
#include <iomanip>
#include <sstream>
#include <utility>

namespace nengine::scripting {
namespace {

void set_error(
    std::string* error,
    std::string message) {

    if (error) {
        *error = std::move(message);
    }
}

std::string xml_escape(
    std::string_view value) {

    std::string result;
    result.reserve(value.size());

    for (const char ch : value) {
        switch (ch) {
        case '&': result += "&amp;"; break;
        case '<': result += "&lt;"; break;
        case '>': result += "&gt;"; break;
        case '"': result += "&quot;"; break;
        case '\'': result += "&apos;"; break;
        default: result.push_back(ch); break;
        }
    }

    return result;
}

std::string csharp_escape(
    std::string_view value) {

    std::string result;
    result.reserve(
        value.size());

    for (const char ch : value) {
        switch (ch) {
        case '\\':
            result += "\\\\";
            break;
        case '"':
            result += "\\\"";
            break;
        case '\n':
            result += "\\n";
            break;
        case '\r':
            result += "\\r";
            break;
        case '\t':
            result += "\\t";
            break;
        default:
            result.push_back(ch);
            break;
        }
    }

    return result;
}

bool write_text(
    const std::filesystem::path& path,
    std::string_view text,
    std::string* error) {

    std::ofstream output(
        path,
        std::ios::binary | std::ios::trunc);

    if (!output) {
        set_error(
            error,
            "could not open generated file: " +
                path.generic_string());
        return false;
    }

    output.write(
        text.data(),
        static_cast<std::streamsize>(
            text.size()));

    if (!output.good()) {
        set_error(
            error,
            "failed writing generated file: " +
                path.generic_string());
        return false;
    }

    return true;
}

std::string managed_bridge() {
    return R"CS(// Generated by NEngine. Do not edit.
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.Loader;
using System.Text;

namespace NEngine.Internal
{
    internal sealed class GameplayLoadContext : AssemblyLoadContext
    {
        private readonly AssemblyDependencyResolver _resolver;
        private readonly Assembly _apiAssembly;
        private readonly Assembly _bridgeAssembly;

        public GameplayLoadContext(
            string mainAssemblyPath,
            Assembly apiAssembly,
            Assembly bridgeAssembly)
            : base("NEngine.Gameplay", isCollectible: true)
        {
            _resolver = new AssemblyDependencyResolver(mainAssemblyPath);
            _apiAssembly = apiAssembly;
            _bridgeAssembly = bridgeAssembly;
        }

        protected override Assembly? Load(AssemblyName assemblyName)
        {
            if (string.Equals(
                    assemblyName.Name,
                    _apiAssembly.GetName().Name,
                    StringComparison.Ordinal))
            {
                return _apiAssembly;
            }

            if (string.Equals(
                    assemblyName.Name,
                    _bridgeAssembly.GetName().Name,
                    StringComparison.Ordinal))
            {
                return _bridgeAssembly;
            }

            string? path = _resolver.ResolveAssemblyToPath(assemblyName);
            return path == null
                ? null
                : LoadFromAssemblyPath(path);
        }

        protected override nint LoadUnmanagedDll(string unmanagedDllName)
        {
            string? path = _resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
            return path == null
                ? 0
                : LoadUnmanagedDllFromPath(path);
        }
    }

    public static class NativeBridge
    {
        public const int AbiVersion = 5;

        private static readonly Dictionary<long, NEngine.Behaviour> Instances = new();
        private static long _nextHandle = 1;
        private static GameplayLoadContext? _gameplayContext;
        private static Assembly? _gameplayAssembly;
        private static WeakReference? _previousLoadContext;
        private static string _assemblyName = string.Empty;

        [UnmanagedCallersOnly]
        public static int GetAbiVersion() => AbiVersion;

        [UnmanagedCallersOnly]
        public static int LoadGameplayAssembly(nint assemblyPathUtf8, nint assemblyNameUtf8)
        {
            if (assemblyPathUtf8 == 0 || assemblyNameUtf8 == 0) return -1;
            if (Instances.Count != 0 || _gameplayContext != null) return -2;

            try
            {
                string? rawPath = Marshal.PtrToStringUTF8(assemblyPathUtf8);
                string? expectedName = Marshal.PtrToStringUTF8(assemblyNameUtf8);

                if (string.IsNullOrWhiteSpace(rawPath) ||
                    string.IsNullOrWhiteSpace(expectedName))
                {
                    return -3;
                }

                string fullPath = Path.GetFullPath(rawPath);
                if (!File.Exists(fullPath)) return -4;

                var context = new GameplayLoadContext(
                    fullPath,
                    typeof(NEngine.Behaviour).Assembly,
                    typeof(NativeBridge).Assembly);

                Assembly assembly =
                    context.LoadFromAssemblyPath(fullPath);
                string actualName = assembly.GetName().Name ?? string.Empty;

                if (!string.Equals(actualName, expectedName, StringComparison.Ordinal))
                {
                    context.Unload();
                    return -5;
                }

                _gameplayContext = context;
                _gameplayAssembly = assembly;
                _assemblyName = actualName;
                return 1;
            }
            catch
            {
                _gameplayContext = null;
                _gameplayAssembly = null;
                _assemblyName = string.Empty;
                return -6;
            }
        }

        [UnmanagedCallersOnly]
        public static int UnloadGameplayAssembly()
        {
            if (Instances.Count != 0) return -1;

            try
            {
                GameplayLoadContext? context = _gameplayContext;

                _gameplayAssembly = null;
                _gameplayContext = null;
                _assemblyName = string.Empty;

                if (context == null) return 1;

                _previousLoadContext = new WeakReference(context);
                context.Unload();
                context = null;

                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                return 1;
            }
            catch
            {
                return -2;
            }
        }

        [UnmanagedCallersOnly]
        public static int IsGameplayAssemblyLoaded() =>
            _gameplayAssembly != null ? 1 : 0;

        [UnmanagedCallersOnly]
        public static int IsPreviousLoadContextAlive() =>
            _previousLoadContext?.IsAlive == true ? 1 : 0;

        [UnmanagedCallersOnly]
        public static long CreateBehaviour(nint typeNameUtf8)
        {
            try
            {
                if (_gameplayAssembly == null) return 0;

                string? typeName = Marshal.PtrToStringUTF8(typeNameUtf8);
                if (string.IsNullOrWhiteSpace(typeName)) return 0;

                Type? type = _gameplayAssembly.GetType(typeName, false, false);
                if (type == null ||
                    type.IsAbstract ||
                    !typeof(NEngine.Behaviour).IsAssignableFrom(type))
                {
                    return 0;
                }

                if (Activator.CreateInstance(type) is not NEngine.Behaviour instance)
                    return 0;

                var gameObject = new NEngine.GameObject { name = type.Name };
                gameObject.Attach(instance);

                long handle = _nextHandle++;
                if (handle <= 0)
                {
                    _nextHandle = 2;
                    handle = 1;
                }

                Instances[handle] = instance;
                return handle;
            }
            catch
            {
                return 0;
            }
        }

        private static int Invoke(long handle, string methodName)
        {
            if (!Instances.TryGetValue(handle, out var instance)) return -1;
            if (!instance.enabled && methodName != "OnDestroy") return 0;

            try
            {
                MethodInfo? method = instance.GetType().GetMethod(
                    methodName,
                    BindingFlags.Instance |
                    BindingFlags.Public |
                    BindingFlags.NonPublic,
                    binder: null,
                    types: Type.EmptyTypes,
                    modifiers: null);

                if (method == null) return 0;

                method.Invoke(instance, null);
                return 1;
            }
            catch
            {
                return -2;
            }
        }

        [UnmanagedCallersOnly]
        public static int InvokeStart(long handle) =>
            Invoke(handle, "Start");

        [UnmanagedCallersOnly]
        public static int InvokeUpdate(long handle, float deltaTime)
        {
            NEngine.Time.SetDeltaTime(deltaTime);
            return Invoke(handle, "Update");
        }

        [UnmanagedCallersOnly]
        public static int DestroyBehaviour(long handle)
        {
            if (!Instances.ContainsKey(handle)) return -1;

            int invoked = Invoke(handle, "OnDestroy");
            Instances.Remove(handle);

            return invoked < 0
                ? invoked
                : 1;
        }

        [UnmanagedCallersOnly]
        public static int GetInstanceCount() =>
            Instances.Count;

        [StructLayout(LayoutKind.Sequential)]
        private struct NativeTransformState
        {
            public float px, py, pz;
            public float rx, ry, rz, rw;
            public float sx, sy, sz;
        }

        [UnmanagedCallersOnly]
        public static int SetTransformState(long handle, nint statePtr)
        {
            if (statePtr == 0 ||
                !Instances.TryGetValue(handle, out var instance))
            {
                return -1;
            }

            try
            {
                NativeTransformState state =
                    Marshal.PtrToStructure<NativeTransformState>(statePtr);

                var transform = instance.transform;
                transform.localPosition =
                    new NEngine.Vector3(state.px, state.py, state.pz);
                transform.localRotation =
                    new NEngine.Quaternion(state.rx, state.ry, state.rz, state.rw);
                transform.localScale =
                    new NEngine.Vector3(state.sx, state.sy, state.sz);
                return 1;
            }
            catch
            {
                return -2;
            }
        }

        [UnmanagedCallersOnly]
        public static int GetTransformState(long handle, nint statePtr)
        {
            if (statePtr == 0 ||
                !Instances.TryGetValue(handle, out var instance))
            {
                return -1;
            }

            try
            {
                var transform = instance.transform;

                NativeTransformState state = new NativeTransformState
                {
                    px = transform.localPosition.x,
                    py = transform.localPosition.y,
                    pz = transform.localPosition.z,
                    rx = transform.localRotation.x,
                    ry = transform.localRotation.y,
                    rz = transform.localRotation.z,
                    rw = transform.localRotation.w,
                    sx = transform.localScale.x,
                    sy = transform.localScale.y,
                    sz = transform.localScale.z
                };

                Marshal.StructureToPtr(state, statePtr, false);
                return 1;
            }
            catch
            {
                return -2;
            }
        }

        [StructLayout(LayoutKind.Sequential)]
        private struct NativeGameObjectState
        {
            public ulong entityId;
            public int active;
            public int nameBytes;
        }

        [UnmanagedCallersOnly]
        public static int SetGameObjectState(
            long handle,
            ulong entityId,
            int active,
            nint nameUtf8)
        {
            if (!Instances.TryGetValue(handle, out var instance))
                return -1;

            try
            {
                string name =
                    nameUtf8 == 0
                        ? string.Empty
                        : Marshal.PtrToStringUTF8(nameUtf8) ?? string.Empty;

                instance.gameObject.SetNativeState(
                    entityId,
                    name,
                    active != 0);

                return 1;
            }
            catch
            {
                return -2;
            }
        }

        [UnmanagedCallersOnly]
        public static int GetGameObjectState(long handle, nint statePtr)
        {
            if (statePtr == 0 ||
                !Instances.TryGetValue(handle, out var instance))
            {
                return -1;
            }

            try
            {
                string name =
                    instance.gameObject.name ?? string.Empty;

                NativeGameObjectState state = new NativeGameObjectState
                {
                    entityId = instance.gameObject.instanceId,
                    active = instance.gameObject.activeSelf ? 1 : 0,
                    nameBytes = Encoding.UTF8.GetByteCount(name) + 1
                };

                Marshal.StructureToPtr(state, statePtr, false);
                return 1;
            }
            catch
            {
                return -2;
            }
        }

        [UnmanagedCallersOnly]
        public static int CopyGameObjectNameUtf8(
            long handle,
            nint buffer,
            int capacity)
        {
            if (!Instances.TryGetValue(handle, out var instance))
                return -1;

            try
            {
                byte[] bytes =
                    Encoding.UTF8.GetBytes(
                        instance.gameObject.name ?? string.Empty);

                int required = bytes.Length + 1;

                if (buffer == 0 || capacity < required)
                    return -required;

                if (bytes.Length != 0)
                    Marshal.Copy(bytes, 0, buffer, bytes.Length);

                Marshal.WriteByte(buffer, bytes.Length, 0);
                return required;
            }
            catch
            {
                return -2;
            }
        }

        public static string AssemblyName =>
            _assemblyName;
    }
}
)CS";
}

std::string api_stub(
    std::string_view friend_assembly) {

    std::ostringstream source;

    source
        << "// Generated by NEngine. Do not edit.\n"
        << "using System;\n"
        << "[assembly: System.Runtime.CompilerServices.InternalsVisibleTo(\""
        << csharp_escape(friend_assembly)
        << "\")]\n\n"
        << R"CS(namespace NEngine
{
    public abstract class Component
    {
        public GameObject gameObject { get; internal set; } = null!;
        public Transform transform => gameObject.transform;
        public T? GetComponent<T>() where T : Component => gameObject.GetComponent<T>();
    }

    public abstract class Behaviour : Component
    {
        public bool enabled { get; set; } = true;
    }

    public sealed class GameObject
    {
        private readonly System.Collections.Generic.List<Component> _components = new();
        private string _name = "GameObject";
        private bool _activeSelf = true;
        private ulong _instanceId;

        public string name
        {
            get => _name;
            set => _name = value ?? string.Empty;
        }

        public bool activeSelf => _activeSelf;
        public ulong instanceId => _instanceId;
        public Transform transform { get; }

        public GameObject()
        {
            transform = new Transform();
            Attach(transform);
        }

        internal void Attach(Component component)
        {
            component.gameObject = this;

            if (!_components.Contains(component))
                _components.Add(component);
        }

        internal void SetNativeState(
            ulong instanceId,
            string name,
            bool active)
        {
            _instanceId = instanceId;
            _name = name ?? string.Empty;
            _activeSelf = active;
        }

        public ulong GetInstanceID() => _instanceId;

        public void SetActive(bool active) =>
            _activeSelf = active;

        public T? GetComponent<T>() where T : Component
        {
            foreach (var component in _components)
                if (component is T typed)
                    return typed;

            return null;
        }

        public T AddComponent<T>() where T : Component, new()
        {
            var component = new T();
            Attach(component);
            return component;
        }
    }

    public sealed class Transform : Component
    {
        public Vector3 localPosition { get; set; }
        public Vector3 position
        {
            get => localPosition;
            set => localPosition = value;
        }
        public Vector3 localScale { get; set; } = Vector3.one;
        public Quaternion localRotation { get; set; } = Quaternion.identity;
        public Vector3 forward => Vector3.forward;
    }

    public readonly struct Vector3
    {
        public readonly float x;
        public readonly float y;
        public readonly float z;

        public Vector3(float x, float y, float z)
        {
            this.x = x; this.y = y; this.z = z;
        }

        public static Vector3 zero => new Vector3(0, 0, 0);
        public static Vector3 one => new Vector3(1, 1, 1);
        public static Vector3 forward => new Vector3(0, 0, 1);

        public static Vector3 operator +(Vector3 a, Vector3 b) =>
            new Vector3(a.x + b.x, a.y + b.y, a.z + b.z);

        public static Vector3 operator *(Vector3 a, float b) =>
            new Vector3(a.x * b, a.y * b, a.z * b);
    }

    public readonly struct Quaternion
    {
        public readonly float x;
        public readonly float y;
        public readonly float z;
        public readonly float w;

        public Quaternion(float x, float y, float z, float w)
        {
            this.x = x; this.y = y; this.z = z; this.w = w;
        }

        public static Quaternion identity => new Quaternion(0, 0, 0, 1);
    }

    public static class Time
    {
        public static float deltaTime { get; private set; } = 0.0166667f;
        public static float fixedDeltaTime { get; internal set; } = 0.02f;

        internal static void SetDeltaTime(float value)
        {
            deltaTime = value >= 0 && float.IsFinite(value) ? value : 0;
        }
    }

    public static class Debug
    {
        public static void Log(object? message) { }
        public static void LogWarning(object? message) { }
        public static void LogError(object? message) { }
    }
}
)CS";

    return source.str();
}

} // namespace

bool ManagedProjectGenerator::generate(
    const ManagedProjectConfig& config,
    ManagedProjectOutput& output,
    std::string* error) {

    if (config.project_root.empty() ||
        config.project_name.empty() ||
        config.target_framework.empty() ||
        config.runtime_framework_version.empty()) {
        set_error(
            error,
            "managed project requires project root and name");
        return false;
    }

    const auto generated_directory =
        config.project_root /
        ".nengine" /
        "Managed";

    std::error_code ec;
    std::filesystem::create_directories(
        generated_directory,
        ec);

    if (ec) {
        set_error(
            error,
            "could not create managed generation directory");
        return false;
    }

    output.project_path =
        generated_directory /
        (config.project_name + ".csproj");

    output.api_project_path =
        generated_directory /
        "NEngine.API.csproj";

    output.api_stub_path =
        generated_directory /
        "NEngine.API.cs";

    output.bridge_project_path =
        generated_directory /
        "NEngine.Bridge.csproj";

    output.bridge_path =
        generated_directory /
        "NEngine.ManagedBridge.cs";

    output.runtime_config_path =
        generated_directory /
        (config.project_name +
         ".runtimeconfig.json");

    output.solution_path =
        config.project_root /
        (config.project_name + ".sln");

    std::ostringstream project;

    project
        << "<Project Sdk=\"Microsoft.NET.Sdk\">\n"
        << "  <PropertyGroup>\n"
        << "    <TargetFramework>"
        << xml_escape(
            config.target_framework)
        << "</TargetFramework>\n"
        << "    <LangVersion>latest</LangVersion>\n"
        << "    <Nullable>enable</Nullable>\n"
        << "    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>\n"
        << "    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>\n"
        << "    <AssemblyName>"
        << xml_escape(config.project_name)
        << "</AssemblyName>\n"
        << "  </PropertyGroup>\n"
        << "  <ItemGroup>\n"
        << "    <Compile Include=\"../../Assets/Scripts/**/*.cs\" />\n"
        << "  </ItemGroup>\n"
        << "  <ItemGroup>\n"
        << "    <ProjectReference Include=\"NEngine.API.csproj\" />\n"
        << "    <ProjectReference Include=\"NEngine.Bridge.csproj\" ReferenceOutputAssembly=\"false\" />\n"
        << "  </ItemGroup>\n";

    std::ostringstream api_project;

    api_project
        << "<Project Sdk=\"Microsoft.NET.Sdk\">\n"
        << "  <PropertyGroup>\n"
        << "    <TargetFramework>"
        << xml_escape(
            config.target_framework)
        << "</TargetFramework>\n"
        << "    <LangVersion>latest</LangVersion>\n"
        << "    <Nullable>enable</Nullable>\n"
        << "    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>\n"
        << "    <AssemblyName>NEngine.API</AssemblyName>\n"
        << "  </PropertyGroup>\n"
        << "  <ItemGroup>\n"
        << "    <Compile Include=\"NEngine.API.cs\" />\n"
        << "  </ItemGroup>\n"
        << "</Project>\n";

    std::ostringstream bridge_project;

    bridge_project
        << "<Project Sdk=\"Microsoft.NET.Sdk\">\n"
        << "  <PropertyGroup>\n"
        << "    <TargetFramework>"
        << xml_escape(
            config.target_framework)
        << "</TargetFramework>\n"
        << "    <LangVersion>latest</LangVersion>\n"
        << "    <Nullable>enable</Nullable>\n"
        << "    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>\n"
        << "    <AssemblyName>NEngine.Bridge</AssemblyName>\n"
        << "  </PropertyGroup>\n"
        << "  <ItemGroup>\n"
        << "    <Compile Include=\"NEngine.ManagedBridge.cs\" />\n"
        << "    <ProjectReference Include=\"NEngine.API.csproj\" />\n"
        << "  </ItemGroup>\n"
        << "</Project>\n";

    if (!config.packages.empty()) {
        project << "  <ItemGroup>\n";

        for (const auto& package :
             config.packages) {

            if (package.id.empty() ||
                package.version.empty()) {
                continue;
            }

            project
                << "    <PackageReference Include=\""
                << xml_escape(package.id)
                << "\" Version=\""
                << xml_escape(package.version)
                << "\" />\n";
        }

        project << "  </ItemGroup>\n";
    }

    project << "</Project>\n";

    constexpr std::string_view project_guid =
        "{A5DFE48B-DBA9-4B57-A5D2-E8FBA5903B35}";

    constexpr std::string_view api_project_guid =
        "{4E1A67CE-8C2A-4BC0-9813-9A62154E9B43}";

    constexpr std::string_view bridge_project_guid =
        "{C731B50F-76D6-4A42-9E1D-24F40C28AA2E}";

    std::ostringstream solution;

    solution
        << "Microsoft Visual Studio Solution File, Format Version 12.00\r\n"
        << "# Visual Studio Version 17\r\n"
        << "VisualStudioVersion = 17.0.31903.59\r\n"
        << "MinimumVisualStudioVersion = 10.0.40219.1\r\n"
        << "Project(\"{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}\") = \""
        << config.project_name
        << "\", \".nengine\\Managed\\"
        << config.project_name
        << ".csproj\", \""
        << project_guid
        << "\"\r\n"
        << "EndProject\r\n"
        << "Project(\"{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}\") = \"NEngine.API\", \".nengine\\Managed\\NEngine.API.csproj\", \""
        << api_project_guid
        << "\"\r\n"
        << "EndProject\r\n"
        << "Project(\"{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}\") = \"NEngine.Bridge\", \".nengine\\Managed\\NEngine.Bridge.csproj\", \""
        << bridge_project_guid
        << "\"\r\n"
        << "EndProject\r\n"
        << "Global\r\n"
        << "\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\r\n"
        << "\t\tDebug|Any CPU = Debug|Any CPU\r\n"
        << "\t\tRelease|Any CPU = Release|Any CPU\r\n"
        << "\tEndGlobalSection\r\n"
        << "\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\r\n"
        << "\t\t" << project_guid << ".Debug|Any CPU.ActiveCfg = Debug|Any CPU\r\n"
        << "\t\t" << project_guid << ".Debug|Any CPU.Build.0 = Debug|Any CPU\r\n"
        << "\t\t" << project_guid << ".Release|Any CPU.ActiveCfg = Release|Any CPU\r\n"
        << "\t\t" << project_guid << ".Release|Any CPU.Build.0 = Release|Any CPU\r\n"
        << "\t\t" << api_project_guid << ".Debug|Any CPU.ActiveCfg = Debug|Any CPU\r\n"
        << "\t\t" << api_project_guid << ".Debug|Any CPU.Build.0 = Debug|Any CPU\r\n"
        << "\t\t" << api_project_guid << ".Release|Any CPU.ActiveCfg = Release|Any CPU\r\n"
        << "\t\t" << api_project_guid << ".Release|Any CPU.Build.0 = Release|Any CPU\r\n"
        << "\t\t" << bridge_project_guid << ".Debug|Any CPU.ActiveCfg = Debug|Any CPU\r\n"
        << "\t\t" << bridge_project_guid << ".Debug|Any CPU.Build.0 = Debug|Any CPU\r\n"
        << "\t\t" << bridge_project_guid << ".Release|Any CPU.ActiveCfg = Release|Any CPU\r\n"
        << "\t\t" << bridge_project_guid << ".Release|Any CPU.Build.0 = Release|Any CPU\r\n"
        << "\tEndGlobalSection\r\n"
        << "EndGlobal\r\n";

    if (!write_text(
            output.api_stub_path,
            api_stub(
                "NEngine.Bridge"),
            error)) {
        return false;
    }

    if (!write_text(
            output.bridge_path,
            managed_bridge(),
            error)) {
        return false;
    }

    DotnetRuntimeConfig runtime_config;
    runtime_config.target_framework =
        config.target_framework;
    runtime_config.framework_version =
        config.runtime_framework_version;

    if (!write_dotnet_runtime_config(
            output.runtime_config_path,
            runtime_config,
            error)) {
        return false;
    }

    if (!write_text(
            output.api_project_path,
            api_project.str(),
            error)) {
        return false;
    }

    if (!write_text(
            output.bridge_project_path,
            bridge_project.str(),
            error)) {
        return false;
    }

    if (!write_text(
            output.project_path,
            project.str(),
            error)) {
        return false;
    }

    if (!write_text(
            output.solution_path,
            solution.str(),
            error)) {
        return false;
    }

    return true;
}

std::vector<NuGetPackageReference>
ManagedProjectGenerator::load_package_manifest(
    const std::filesystem::path& path,
    std::string* error) {

    std::vector<NuGetPackageReference> result;

    std::ifstream input(
        path,
        std::ios::binary);

    if (!input) {
        return result;
    }

    std::string id;
    std::string version;

    while (input >> id >> version) {
        if (!id.empty() &&
            id.front() == '#') {

            std::string ignored;
            std::getline(input, ignored);
            continue;
        }

        if (id.empty() ||
            version.empty()) {
            continue;
        }

        result.push_back({
            std::move(id),
            std::move(version)
        });
    }

    if (!input.eof() && input.fail()) {
        set_error(
            error,
            "managed package manifest parse failed");
    }

    return result;
}

} // namespace nengine::scripting
