#include "nengine/scripting/managed_project.hpp"
#include "nengine/scripting/dotnet_host.hpp"

#include <fstream>
#include <iomanip>
#include <sstream>
#include <utility>

namespace nengine::scripting {
namespace {

void set_error(
    std::string* error,
    std::string message) {

    if (error) {
        *error = std::move(message);
    }
}

std::string xml_escape(
    std::string_view value) {

    std::string result;
    result.reserve(value.size());

    for (const char ch : value) {
        switch (ch) {
        case '&': result += "&amp;"; break;
        case '<': result += "&lt;"; break;
        case '>': result += "&gt;"; break;
        case '"': result += "&quot;"; break;
        case '\'': result += "&apos;"; break;
        default: result.push_back(ch); break;
        }
    }

    return result;
}

bool write_text(
    const std::filesystem::path& path,
    std::string_view text,
    std::string* error) {

    std::ofstream output(
        path,
        std::ios::binary | std::ios::trunc);

    if (!output) {
        set_error(
            error,
            "could not open generated file: " +
                path.generic_string());
        return false;
    }

    output.write(
        text.data(),
        static_cast<std::streamsize>(
            text.size()));

    if (!output.good()) {
        set_error(
            error,
            "failed writing generated file: " +
                path.generic_string());
        return false;
    }

    return true;
}

std::string managed_bridge(
    std::string_view assembly_name) {

    std::ostringstream source;

    source
        << "// Generated by NEngine. Do not edit.\n"
        << "using System.Runtime.InteropServices;\n\n"
        << "namespace NEngine.Internal\n"
        << "{\n"
        << "    public static class NativeBridge\n"
        << "    {\n"
        << "        public const int AbiVersion = 1;\n\n"
        << "        [UnmanagedCallersOnly]\n"
        << "        public static int GetAbiVersion() => AbiVersion;\n\n"
        << "        public static string AssemblyName => \""
        << assembly_name
        << "\";\n"
        << "    }\n"
        << "}\n";

    return source.str();
}

std::string api_stub() {
    return R"CS(// Generated by NEngine. Do not edit.
using System;

namespace NEngine
{
    public abstract class Component
    {
        public GameObject gameObject { get; internal set; } = null!;
        public Transform transform => gameObject.transform;
        public T? GetComponent<T>() where T : Component => gameObject.GetComponent<T>();
    }

    public abstract class Behaviour : Component
    {
        public bool enabled { get; set; } = true;
    }

    public sealed class GameObject
    {
        public string name { get; set; } = "GameObject";
        public bool activeSelf { get; private set; } = true;
        public Transform transform { get; } = new Transform();

        public void SetActive(bool active) => activeSelf = active;
        public T? GetComponent<T>() where T : Component => default;
        public T AddComponent<T>() where T : Component, new() => new T();
    }

    public sealed class Transform : Component
    {
        public Vector3 position { get; set; }
        public Vector3 localPosition { get; set; }
        public Vector3 localScale { get; set; } = Vector3.one;
        public Quaternion localRotation { get; set; } = Quaternion.identity;
        public Vector3 forward => Vector3.forward;
    }

    public readonly struct Vector3
    {
        public readonly float x;
        public readonly float y;
        public readonly float z;

        public Vector3(float x, float y, float z)
        {
            this.x = x; this.y = y; this.z = z;
        }

        public static Vector3 zero => new Vector3(0, 0, 0);
        public static Vector3 one => new Vector3(1, 1, 1);
        public static Vector3 forward => new Vector3(0, 0, 1);

        public static Vector3 operator +(Vector3 a, Vector3 b) =>
            new Vector3(a.x + b.x, a.y + b.y, a.z + b.z);

        public static Vector3 operator *(Vector3 a, float b) =>
            new Vector3(a.x * b, a.y * b, a.z * b);
    }

    public readonly struct Quaternion
    {
        public readonly float x;
        public readonly float y;
        public readonly float z;
        public readonly float w;

        public Quaternion(float x, float y, float z, float w)
        {
            this.x = x; this.y = y; this.z = z; this.w = w;
        }

        public static Quaternion identity => new Quaternion(0, 0, 0, 1);
    }

    public static class Time
    {
        public static float deltaTime => 0.0166667f;
        public static float fixedDeltaTime => 0.02f;
    }

    public static class Debug
    {
        public static void Log(object? message) { }
        public static void LogWarning(object? message) { }
        public static void LogError(object? message) { }
    }
}
)CS";
}

} // namespace

bool ManagedProjectGenerator::generate(
    const ManagedProjectConfig& config,
    ManagedProjectOutput& output,
    std::string* error) {

    if (config.project_root.empty() ||
        config.project_name.empty() ||
        config.target_framework.empty() ||
        config.runtime_framework_version.empty()) {
        set_error(
            error,
            "managed project requires project root and name");
        return false;
    }

    const auto generated_directory =
        config.project_root /
        ".nengine" /
        "Managed";

    std::error_code ec;
    std::filesystem::create_directories(
        generated_directory,
        ec);

    if (ec) {
        set_error(
            error,
            "could not create managed generation directory");
        return false;
    }

    output.project_path =
        generated_directory /
        (config.project_name + ".csproj");

    output.api_stub_path =
        generated_directory /
        "NEngine.API.cs";

    output.bridge_path =
        generated_directory /
        "NEngine.ManagedBridge.cs";

    output.runtime_config_path =
        generated_directory /
        (config.project_name +
         ".runtimeconfig.json");

    output.solution_path =
        config.project_root /
        (config.project_name + ".sln");

    std::ostringstream project;

    project
        << "<Project Sdk=\"Microsoft.NET.Sdk\">\n"
        << "  <PropertyGroup>\n"
        << "    <TargetFramework>"
        << xml_escape(
            config.target_framework)
        << "</TargetFramework>\n"
        << "    <LangVersion>latest</LangVersion>\n"
        << "    <Nullable>enable</Nullable>\n"
        << "    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>\n"
        << "    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>\n"
        << "    <AssemblyName>"
        << xml_escape(config.project_name)
        << "</AssemblyName>\n"
        << "  </PropertyGroup>\n"
        << "  <ItemGroup>\n"
        << "    <Compile Include=\"../../Assets/Scripts/**/*.cs\" />\n"
        << "    <Compile Include=\"NEngine.API.cs\" />\n"
        << "    <Compile Include=\"NEngine.ManagedBridge.cs\" />\n"
        << "  </ItemGroup>\n";

    if (!config.packages.empty()) {
        project << "  <ItemGroup>\n";

        for (const auto& package :
             config.packages) {

            if (package.id.empty() ||
                package.version.empty()) {
                continue;
            }

            project
                << "    <PackageReference Include=\""
                << xml_escape(package.id)
                << "\" Version=\""
                << xml_escape(package.version)
                << "\" />\n";
        }

        project << "  </ItemGroup>\n";
    }

    project << "</Project>\n";

    constexpr std::string_view project_guid =
        "{A5DFE48B-DBA9-4B57-A5D2-E8FBA5903B35}";

    std::ostringstream solution;

    solution
        << "Microsoft Visual Studio Solution File, Format Version 12.00\r\n"
        << "# Visual Studio Version 17\r\n"
        << "VisualStudioVersion = 17.0.31903.59\r\n"
        << "MinimumVisualStudioVersion = 10.0.40219.1\r\n"
        << "Project(\"{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}\") = \""
        << config.project_name
        << "\", \".nengine\\Managed\\"
        << config.project_name
        << ".csproj\", \""
        << project_guid
        << "\"\r\n"
        << "EndProject\r\n"
        << "Global\r\n"
        << "\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\r\n"
        << "\t\tDebug|Any CPU = Debug|Any CPU\r\n"
        << "\t\tRelease|Any CPU = Release|Any CPU\r\n"
        << "\tEndGlobalSection\r\n"
        << "\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\r\n"
        << "\t\t" << project_guid << ".Debug|Any CPU.ActiveCfg = Debug|Any CPU\r\n"
        << "\t\t" << project_guid << ".Debug|Any CPU.Build.0 = Debug|Any CPU\r\n"
        << "\t\t" << project_guid << ".Release|Any CPU.ActiveCfg = Release|Any CPU\r\n"
        << "\t\t" << project_guid << ".Release|Any CPU.Build.0 = Release|Any CPU\r\n"
        << "\tEndGlobalSection\r\n"
        << "EndGlobal\r\n";

    if (!write_text(
            output.api_stub_path,
            api_stub(),
            error)) {
        return false;
    }

    if (!write_text(
            output.bridge_path,
            managed_bridge(
                config.project_name),
            error)) {
        return false;
    }

    DotnetRuntimeConfig runtime_config;
    runtime_config.target_framework =
        config.target_framework;
    runtime_config.framework_version =
        config.runtime_framework_version;

    if (!write_dotnet_runtime_config(
            output.runtime_config_path,
            runtime_config,
            error)) {
        return false;
    }

    if (!write_text(
            output.project_path,
            project.str(),
            error)) {
        return false;
    }

    if (!write_text(
            output.solution_path,
            solution.str(),
            error)) {
        return false;
    }

    return true;
}

std::vector<NuGetPackageReference>
ManagedProjectGenerator::load_package_manifest(
    const std::filesystem::path& path,
    std::string* error) {

    std::vector<NuGetPackageReference> result;

    std::ifstream input(
        path,
        std::ios::binary);

    if (!input) {
        return result;
    }

    std::string id;
    std::string version;

    while (input >> id >> version) {
        if (!id.empty() &&
            id.front() == '#') {

            std::string ignored;
            std::getline(input, ignored);
            continue;
        }

        if (id.empty() ||
            version.empty()) {
            continue;
        }

        result.push_back({
            std::move(id),
            std::move(version)
        });
    }

    if (!input.eof() && input.fail()) {
        set_error(
            error,
            "managed package manifest parse failed");
    }

    return result;
}

} // namespace nengine::scripting
