#include "nengine/scripting/managed_project.hpp"
#include "nengine/scripting/dotnet_host.hpp"

#include <fstream>
#include <iomanip>
#include <sstream>
#include <utility>

namespace nengine::scripting {
namespace {

void set_error(
    std::string* error,
    std::string message) {

    if (error) {
        *error = std::move(message);
    }
}

std::string xml_escape(
    std::string_view value) {

    std::string result;
    result.reserve(value.size());

    for (const char ch : value) {
        switch (ch) {
        case '&': result += "&amp;"; break;
        case '<': result += "&lt;"; break;
        case '>': result += "&gt;"; break;
        case '"': result += "&quot;"; break;
        case '\'': result += "&apos;"; break;
        default: result.push_back(ch); break;
        }
    }

    return result;
}

std::string csharp_escape(
    std::string_view value) {

    std::string result;
    result.reserve(
        value.size());

    for (const char ch : value) {
        switch (ch) {
        case '\\':
            result += "\\\\";
            break;
        case '"':
            result += "\\\"";
            break;
        case '\n':
            result += "\\n";
            break;
        case '\r':
            result += "\\r";
            break;
        case '\t':
            result += "\\t";
            break;
        default:
            result.push_back(ch);
            break;
        }
    }

    return result;
}

bool write_text(
    const std::filesystem::path& path,
    std::string_view text,
    std::string* error) {

    std::ofstream output(
        path,
        std::ios::binary | std::ios::trunc);

    if (!output) {
        set_error(
            error,
            "could not open generated file: " +
                path.generic_string());
        return false;
    }

    output.write(
        text.data(),
        static_cast<std::streamsize>(
            text.size()));

    if (!output.good()) {
        set_error(
            error,
            "failed writing generated file: " +
                path.generic_string());
        return false;
    }

    return true;
}

std::string managed_bridge() {
    return R"CS(// Generated by NEngine. Do not edit.
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.Loader;
using System.Text;

namespace NEngine.Internal
{
    internal sealed class GameplayLoadContext : AssemblyLoadContext
    {
        private readonly AssemblyDependencyResolver _resolver;
        private readonly Assembly _apiAssembly;
        private readonly Assembly _bridgeAssembly;

        public GameplayLoadContext(
            string mainAssemblyPath,
            Assembly apiAssembly,
            Assembly bridgeAssembly)
            : base("NEngine.Gameplay", isCollectible: true)
        {
            _resolver = new AssemblyDependencyResolver(mainAssemblyPath);
            _apiAssembly = apiAssembly;
            _bridgeAssembly = bridgeAssembly;
        }

        protected override Assembly? Load(AssemblyName assemblyName)
        {
            if (string.Equals(
                    assemblyName.Name,
                    _apiAssembly.GetName().Name,
                    StringComparison.Ordinal))
            {
                return _apiAssembly;
            }

            if (string.Equals(
                    assemblyName.Name,
                    _bridgeAssembly.GetName().Name,
                    StringComparison.Ordinal))
            {
                return _bridgeAssembly;
            }

            string? path = _resolver.ResolveAssemblyToPath(assemblyName);
            return path == null
                ? null
                : LoadFromAssemblyPath(path);
        }

        protected override nint LoadUnmanagedDll(string unmanagedDllName)
        {
            string? path = _resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
            return path == null
                ? 0
                : LoadUnmanagedDllFromPath(path);
        }
    }

    public static class NativeBridge
    {
        public const int AbiVersion = 7;

        private static readonly Dictionary<long, NEngine.Behaviour> Instances = new();
        private static long _nextHandle = 1;
        private static GameplayLoadContext? _gameplayContext;
        private static Assembly? _gameplayAssembly;
        private static WeakReference? _previousLoadContext;
        private static string _assemblyName = string.Empty;

        [UnmanagedCallersOnly]
        public static int GetAbiVersion() => AbiVersion;
        [StructLayout(LayoutKind.Sequential)]
        private struct NativeWorldCallbacks
        {
            public nint context;
            public nint create;
            public nint destroy;
            public nint find;
            public nint isAlive;
            public nint copyNameUtf8;
            public nint setNameUtf8;
            public nint getActive;
            public nint setActive;
            public nint getTransform;
            public nint setTransform;
            public nint getParent;
            public nint setParent;
            public nint getChildCount;
            public nint getChildAt;
            public nint hasComponent;
        }

        [UnmanagedCallersOnly]
        public static int ConfigureNativeWorldCallbacks(nint callbacksPtr)
        {
            try
            {
                if (callbacksPtr == 0)
                {
                    NEngine.NativeWorld.Clear();
                    return 1;
                }

                NativeWorldCallbacks callbacks =
                    Marshal.PtrToStructure<NativeWorldCallbacks>(callbacksPtr);

                NEngine.NativeWorld.Configure(
                    callbacks.context,
                    callbacks.create,
                    callbacks.destroy,
                    callbacks.find,
                    callbacks.isAlive,
                    callbacks.copyNameUtf8,
                    callbacks.setNameUtf8,
                    callbacks.getActive,
                    callbacks.setActive,
                    callbacks.getTransform,
                    callbacks.setTransform,
                    callbacks.getParent,
                    callbacks.setParent,
                    callbacks.getChildCount,
                    callbacks.getChildAt,
                    callbacks.hasComponent);

                return 1;
            }
            catch
            {
                NEngine.NativeWorld.Clear();
                return -1;
            }
        }


        [StructLayout(LayoutKind.Sequential)]
        private struct NativeInputCallbacks
        {
            public nint context;
            public nint held;
            public nint pressed;
            public nint released;
            public nint pointer;
        }

        [UnmanagedCallersOnly]
        public static int ConfigureNativeInputCallbacks(nint callbacksPtr)
        {
            try
            {
                if (callbacksPtr == 0)
                {
                    NEngine.NativeInput.Clear();
                    return 1;
                }

                NativeInputCallbacks callbacks =
                    Marshal.PtrToStructure<NativeInputCallbacks>(callbacksPtr);

                NEngine.NativeInput.Configure(
                    callbacks.context,
                    callbacks.held,
                    callbacks.pressed,
                    callbacks.released,
                    callbacks.pointer);

                return 1;
            }
            catch
            {
                NEngine.NativeInput.Clear();
                return -1;
            }
        }


        [UnmanagedCallersOnly]
        public static int LoadGameplayAssembly(nint assemblyPathUtf8, nint assemblyNameUtf8)
        {
            if (assemblyPathUtf8 == 0 || assemblyNameUtf8 == 0) return -1;
            if (Instances.Count != 0 || _gameplayContext != null) return -2;

            try
            {
                string? rawPath = Marshal.PtrToStringUTF8(assemblyPathUtf8);
                string? expectedName = Marshal.PtrToStringUTF8(assemblyNameUtf8);

                if (string.IsNullOrWhiteSpace(rawPath) ||
                    string.IsNullOrWhiteSpace(expectedName))
                {
                    return -3;
                }

                string fullPath = Path.GetFullPath(rawPath);
                if (!File.Exists(fullPath)) return -4;

                var context = new GameplayLoadContext(
                    fullPath,
                    typeof(NEngine.Behaviour).Assembly,
                    typeof(NativeBridge).Assembly);

                Assembly assembly =
                    context.LoadFromAssemblyPath(fullPath);
                string actualName = assembly.GetName().Name ?? string.Empty;

                if (!string.Equals(actualName, expectedName, StringComparison.Ordinal))
                {
                    context.Unload();
                    return -5;
                }

                _gameplayContext = context;
                _gameplayAssembly = assembly;
                _assemblyName = actualName;
                NEngine.Time.Reset();
                return 1;
            }
            catch
            {
                _gameplayContext = null;
                _gameplayAssembly = null;
                _assemblyName = string.Empty;
                return -6;
            }
        }

        [UnmanagedCallersOnly]
        public static int UnloadGameplayAssembly()
        {
            if (Instances.Count != 0) return -1;

            try
            {
                GameplayLoadContext? context = _gameplayContext;

                _gameplayAssembly = null;
                _gameplayContext = null;
                _assemblyName = string.Empty;

                if (context == null) return 1;

                _previousLoadContext = new WeakReference(context);
                context.Unload();
                context = null;

                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                return 1;
            }
            catch
            {
                return -2;
            }
        }

        [UnmanagedCallersOnly]
        public static int IsGameplayAssemblyLoaded() =>
            _gameplayAssembly != null ? 1 : 0;

        [UnmanagedCallersOnly]
        public static int IsPreviousLoadContextAlive() =>
            _previousLoadContext?.IsAlive == true ? 1 : 0;

        [UnmanagedCallersOnly]
        public static long CreateBehaviour(nint typeNameUtf8)
        {
            try
            {
                if (_gameplayAssembly == null) return 0;

                string? typeName = Marshal.PtrToStringUTF8(typeNameUtf8);
                if (string.IsNullOrWhiteSpace(typeName)) return 0;

                Type? type = _gameplayAssembly.GetType(typeName, false, false);
                if (type == null ||
                    type.IsAbstract ||
                    !typeof(NEngine.Behaviour).IsAssignableFrom(type))
                {
                    return 0;
                }

                if (Activator.CreateInstance(type) is not NEngine.Behaviour instance)
                    return 0;

                var gameObject = new NEngine.GameObject(createNative: false) { name = type.Name };
                gameObject.Attach(instance);

                long handle = _nextHandle++;
                if (handle <= 0)
                {
                    _nextHandle = 2;
                    handle = 1;
                }

                Instances[handle] = instance;
                return handle;
            }
            catch
            {
                return 0;
            }
        }

        private static int Invoke(long handle, string methodName)
        {
            if (!Instances.TryGetValue(handle, out var instance)) return -1;
            if (!instance.enabled && methodName != "OnDestroy") return 0;

            try
            {
                MethodInfo? method = instance.GetType().GetMethod(
                    methodName,
                    BindingFlags.Instance |
                    BindingFlags.Public |
                    BindingFlags.NonPublic,
                    binder: null,
                    types: Type.EmptyTypes,
                    modifiers: null);

                if (method == null) return 0;

                method.Invoke(instance, null);
                return 1;
            }
            catch
            {
                return -2;
            }
        }

        [UnmanagedCallersOnly]
        public static int InvokeStart(long handle) =>
            Invoke(handle, "Start");

        [UnmanagedCallersOnly]
        public static int AdvanceFrameClock(float deltaTime)
        {
            if (!float.IsFinite(deltaTime) || deltaTime < 0)
                return -1;

            NEngine.Time.SetDeltaTime(deltaTime);
            return 1;
        }

        [UnmanagedCallersOnly]
        public static int ResetFrameClock()
        {
            NEngine.Time.Reset();
            return 1;
        }

        [UnmanagedCallersOnly]
        public static int InvokeUpdate(long handle, float deltaTime)
        {
            int invoked = Invoke(handle, "Update");
            if (invoked < 0) return invoked;

            if (Instances.TryGetValue(handle, out var instance))
                instance.AdvanceCoroutines(deltaTime);

            return invoked;
        }

        [UnmanagedCallersOnly]
        public static int DestroyBehaviour(long handle)
        {
            if (!Instances.ContainsKey(handle)) return -1;

            int invoked = Invoke(handle, "OnDestroy");

            if (Instances.TryGetValue(handle, out var instance))
                instance.StopAllCoroutines();

            Instances.Remove(handle);

            return invoked < 0
                ? invoked
                : 1;
        }

        [UnmanagedCallersOnly]
        public static int GetInstanceCount() =>
            Instances.Count;

        [StructLayout(LayoutKind.Sequential)]
        private struct NativeTransformState
        {
            public float px, py, pz;
            public float rx, ry, rz, rw;
            public float sx, sy, sz;
        }

        [UnmanagedCallersOnly]
        public static int SetTransformState(long handle, nint statePtr)
        {
            if (statePtr == 0 ||
                !Instances.TryGetValue(handle, out var instance))
            {
                return -1;
            }

            try
            {
                NativeTransformState state =
                    Marshal.PtrToStructure<NativeTransformState>(statePtr);

                instance.transform.SetNativeState(
                    new NEngine.Vector3(state.px, state.py, state.pz),
                    new NEngine.Quaternion(state.rx, state.ry, state.rz, state.rw),
                    new NEngine.Vector3(state.sx, state.sy, state.sz));
                return 1;
            }
            catch
            {
                return -2;
            }
        }

        [UnmanagedCallersOnly]
        public static int GetTransformState(long handle, nint statePtr)
        {
            if (statePtr == 0 ||
                !Instances.TryGetValue(handle, out var instance))
            {
                return -1;
            }

            try
            {
                instance.transform.GetCachedState(
                    out NEngine.Vector3 position,
                    out NEngine.Quaternion rotation,
                    out NEngine.Vector3 scale);

                NativeTransformState state = new NativeTransformState
                {
                    px = position.x,
                    py = position.y,
                    pz = position.z,
                    rx = rotation.x,
                    ry = rotation.y,
                    rz = rotation.z,
                    rw = rotation.w,
                    sx = scale.x,
                    sy = scale.y,
                    sz = scale.z
                };

                Marshal.StructureToPtr(state, statePtr, false);
                return 1;
            }
            catch
            {
                return -2;
            }
        }

        [StructLayout(LayoutKind.Sequential)]
        private struct NativeGameObjectState
        {
            public ulong entityId;
            public int active;
            public int nameBytes;
        }

        [UnmanagedCallersOnly]
        public static int SetGameObjectState(
            long handle,
            ulong entityId,
            int active,
            nint nameUtf8)
        {
            if (!Instances.TryGetValue(handle, out var instance))
                return -1;

            try
            {
                string name =
                    nameUtf8 == 0
                        ? string.Empty
                        : Marshal.PtrToStringUTF8(nameUtf8) ?? string.Empty;

                instance.gameObject.SetNativeState(
                    entityId,
                    name,
                    active != 0);

                return 1;
            }
            catch
            {
                return -2;
            }
        }

        [UnmanagedCallersOnly]
        public static int GetGameObjectState(long handle, nint statePtr)
        {
            if (statePtr == 0 ||
                !Instances.TryGetValue(handle, out var instance))
            {
                return -1;
            }

            try
            {
                string name =
                    instance.gameObject.name ?? string.Empty;

                NativeGameObjectState state = new NativeGameObjectState
                {
                    entityId = instance.gameObject.instanceId,
                    active = instance.gameObject.activeSelf ? 1 : 0,
                    nameBytes = Encoding.UTF8.GetByteCount(name) + 1
                };

                Marshal.StructureToPtr(state, statePtr, false);
                return 1;
            }
            catch
            {
                return -2;
            }
        }

        [UnmanagedCallersOnly]
        public static int CopyGameObjectNameUtf8(
            long handle,
            nint buffer,
            int capacity)
        {
            if (!Instances.TryGetValue(handle, out var instance))
                return -1;

            try
            {
                byte[] bytes =
                    Encoding.UTF8.GetBytes(
                        instance.gameObject.name ?? string.Empty);

                int required = bytes.Length + 1;

                if (buffer == 0 || capacity < required)
                    return -required;

                if (bytes.Length != 0)
                    Marshal.Copy(bytes, 0, buffer, bytes.Length);

                Marshal.WriteByte(buffer, bytes.Length, 0);
                return required;
            }
            catch
            {
                return -2;
            }
        }

        public static string AssemblyName =>
            _assemblyName;
    }
}
)CS";
}

std::string api_stub(
    std::string_view friend_assembly) {

    std::ostringstream source;

    source
        << "// Generated by NEngine. Do not edit.\n"
        << "using System;\n"
        << "using System.Collections;\n"
        << "using System.Collections.Generic;\n"
        << "using System.Runtime.InteropServices;\n"
        << "using System.Text;\n"
        << "[assembly: System.Runtime.CompilerServices.InternalsVisibleTo(\""
        << csharp_escape(friend_assembly)
        << "\")]\n\n"
        << R"CS(namespace NEngine
{
    [StructLayout(LayoutKind.Sequential)]
    internal struct NativeTransformState
    {
        public float px, py, pz;
        public float rx, ry, rz, rw;
        public float sx, sy, sz;
    }

    internal static class NativeWorld
    {
        internal const ulong InvalidEntity = ulong.MaxValue;

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate ulong CreateFn(nint context, nint nameUtf8);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int DestroyFn(nint context, ulong entityId);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate ulong FindFn(nint context, nint nameUtf8);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int IsAliveFn(nint context, ulong entityId);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int CopyNameFn(nint context, ulong entityId, nint buffer, int capacity);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int SetNameFn(nint context, ulong entityId, nint nameUtf8);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int GetActiveFn(nint context, ulong entityId);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int SetActiveFn(nint context, ulong entityId, int active);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int TransformFn(nint context, ulong entityId, ref NativeTransformState state);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate ulong GetParentFn(nint context, ulong entityId);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int SetParentFn(nint context, ulong childId, ulong parentId);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int GetChildCountFn(nint context, ulong entityId);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate ulong GetChildAtFn(nint context, ulong entityId, int index);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int HasComponentFn(nint context, ulong entityId, nint typeNameUtf8);

        private static nint _context;
        private static CreateFn? _create;
        private static DestroyFn? _destroy;
        private static FindFn? _find;
        private static IsAliveFn? _isAlive;
        private static CopyNameFn? _copyName;
        private static SetNameFn? _setName;
        private static GetActiveFn? _getActive;
        private static SetActiveFn? _setActive;
        private static TransformFn? _getTransform;
        private static TransformFn? _setTransform;
        private static GetParentFn? _getParent;
        private static SetParentFn? _setParent;
        private static GetChildCountFn? _getChildCount;
        private static GetChildAtFn? _getChildAt;
        private static HasComponentFn? _hasComponent;

        internal static bool available =>
            _context != 0 &&
            _isAlive != null;

        internal static void Configure(
            nint context,
            nint create,
            nint destroy,
            nint find,
            nint isAlive,
            nint copyName,
            nint setName,
            nint getActive,
            nint setActive,
            nint getTransform,
            nint setTransform,
            nint getParent,
            nint setParent,
            nint getChildCount,
            nint getChildAt,
            nint hasComponent)
        {
            _context = context;
            _create = Marshal.GetDelegateForFunctionPointer<CreateFn>(create);
            _destroy = Marshal.GetDelegateForFunctionPointer<DestroyFn>(destroy);
            _find = Marshal.GetDelegateForFunctionPointer<FindFn>(find);
            _isAlive = Marshal.GetDelegateForFunctionPointer<IsAliveFn>(isAlive);
            _copyName = Marshal.GetDelegateForFunctionPointer<CopyNameFn>(copyName);
            _setName = Marshal.GetDelegateForFunctionPointer<SetNameFn>(setName);
            _getActive = Marshal.GetDelegateForFunctionPointer<GetActiveFn>(getActive);
            _setActive = Marshal.GetDelegateForFunctionPointer<SetActiveFn>(setActive);
            _getTransform = Marshal.GetDelegateForFunctionPointer<TransformFn>(getTransform);
            _setTransform = Marshal.GetDelegateForFunctionPointer<TransformFn>(setTransform);
            _getParent = Marshal.GetDelegateForFunctionPointer<GetParentFn>(getParent);
            _setParent = Marshal.GetDelegateForFunctionPointer<SetParentFn>(setParent);
            _getChildCount = Marshal.GetDelegateForFunctionPointer<GetChildCountFn>(getChildCount);
            _getChildAt = Marshal.GetDelegateForFunctionPointer<GetChildAtFn>(getChildAt);
            _hasComponent = Marshal.GetDelegateForFunctionPointer<HasComponentFn>(hasComponent);
        }

        internal static void Clear()
        {
            _context = 0;
            _create = null;
            _destroy = null;
            _find = null;
            _isAlive = null;
            _copyName = null;
            _setName = null;
            _getActive = null;
            _setActive = null;
            _getTransform = null;
            _setTransform = null;
            _getParent = null;
            _setParent = null;
            _getChildCount = null;
            _getChildAt = null;
            _hasComponent = null;
        }

        private static ulong WithUtf8Entity(
            string value,
            Func<nint, ulong> invoke)
        {
            byte[] bytes = Encoding.UTF8.GetBytes((value ?? string.Empty) + "\0");
            nint buffer = Marshal.AllocHGlobal(bytes.Length);

            try
            {
                Marshal.Copy(bytes, 0, buffer, bytes.Length);
                return invoke(buffer);
            }
            finally
            {
                Marshal.FreeHGlobal(buffer);
            }
        }

        internal static ulong Create(string name) =>
            _create == null
                ? InvalidEntity
                : WithUtf8Entity(
                    name,
                    ptr => _create(_context, ptr));

        internal static bool Destroy(ulong entityId) =>
            _destroy?.Invoke(
                _context,
                entityId) > 0;

        internal static ulong Find(string name) =>
            _find == null
                ? InvalidEntity
                : WithUtf8Entity(
                    name,
                    ptr => _find(_context, ptr));

        internal static bool IsAlive(ulong entityId) =>
            _isAlive?.Invoke(_context, entityId) > 0;

        internal static bool TryGetName(ulong entityId, out string name)
        {
            name = string.Empty;
            if (_copyName == null) return false;

            int first = _copyName(_context, entityId, 0, 0);
            if (first >= 0) return false;

            int required = -first;
            if (required <= 0 || required > 1024 * 1024) return false;

            nint buffer = Marshal.AllocHGlobal(required);
            try
            {
                int copied = _copyName(_context, entityId, buffer, required);
                if (copied <= 0) return false;

                name = Marshal.PtrToStringUTF8(buffer) ?? string.Empty;
                return true;
            }
            finally
            {
                Marshal.FreeHGlobal(buffer);
            }
        }

        private static bool WithUtf8(string value, Func<nint, bool> invoke)
        {
            byte[] bytes = Encoding.UTF8.GetBytes((value ?? string.Empty) + "\0");
            nint buffer = Marshal.AllocHGlobal(bytes.Length);

            try
            {
                Marshal.Copy(bytes, 0, buffer, bytes.Length);
                return invoke(buffer);
            }
            finally
            {
                Marshal.FreeHGlobal(buffer);
            }
        }

        internal static bool SetName(ulong entityId, string value) =>
            _setName != null &&
            WithUtf8(value, ptr => _setName(_context, entityId, ptr) > 0);

        internal static bool TryGetActive(ulong entityId, out bool active)
        {
            active = false;
            if (_getActive == null) return false;

            int value = _getActive(_context, entityId);
            if (value < 0) return false;

            active = value != 0;
            return true;
        }

        internal static bool SetActive(ulong entityId, bool active) =>
            _setActive?.Invoke(_context, entityId, active ? 1 : 0) > 0;

        internal static bool TryGetTransform(
            ulong entityId,
            out NativeTransformState state)
        {
            state = new NativeTransformState();
            return _getTransform?.Invoke(_context, entityId, ref state) > 0;
        }

        internal static bool SetTransform(
            ulong entityId,
            ref NativeTransformState state) =>
            _setTransform?.Invoke(_context, entityId, ref state) > 0;

        internal static ulong GetParent(ulong entityId) =>
            _getParent?.Invoke(_context, entityId) ?? InvalidEntity;

        internal static bool SetParent(ulong childId, ulong parentId) =>
            _setParent?.Invoke(_context, childId, parentId) > 0;

        internal static int GetChildCount(ulong entityId) =>
            _getChildCount?.Invoke(_context, entityId) ?? -1;

        internal static ulong GetChildAt(ulong entityId, int index) =>
            _getChildAt?.Invoke(_context, entityId, index) ?? InvalidEntity;

        internal static bool HasComponent(ulong entityId, string typeName) =>
            _hasComponent != null &&
            WithUtf8(typeName, ptr => _hasComponent(_context, entityId, ptr) > 0);

        internal static string? NativeComponentName(Type type)
        {
            if (type == typeof(Transform)) return "NEngine.Transform";
            if (type == typeof(Camera)) return "NEngine.Camera";
            if (type == typeof(Light)) return "NEngine.Light";
            if (type == typeof(MeshRenderer)) return "NEngine.MeshRenderer";
            if (type == typeof(SpriteRenderer)) return "NEngine.SpriteRenderer";
            return null;
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct NativePointerState
    {
        public float x;
        public float y;
        public float deltaX;
        public float deltaY;
        public float wheelY;
    }

    internal static class NativeInput
    {
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int KeyFn(nint context, uint key);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int PointerFn(nint context, ref NativePointerState state);

        private static nint _context;
        private static KeyFn? _held;
        private static KeyFn? _pressed;
        private static KeyFn? _released;
        private static PointerFn? _pointer;

        internal static void Configure(
            nint context,
            nint held,
            nint pressed,
            nint released,
            nint pointer)
        {
            _context = context;
            _held = Marshal.GetDelegateForFunctionPointer<KeyFn>(held);
            _pressed = Marshal.GetDelegateForFunctionPointer<KeyFn>(pressed);
            _released = Marshal.GetDelegateForFunctionPointer<KeyFn>(released);
            _pointer = Marshal.GetDelegateForFunctionPointer<PointerFn>(pointer);
        }

        internal static void Clear()
        {
            _context = 0;
            _held = null;
            _pressed = null;
            _released = null;
            _pointer = null;
        }

        internal static bool GetKey(uint key) =>
            _held?.Invoke(_context, key) > 0;

        internal static bool GetKeyDown(uint key) =>
            _pressed?.Invoke(_context, key) > 0;

        internal static bool GetKeyUp(uint key) =>
            _released?.Invoke(_context, key) > 0;

        internal static bool TryGetPointer(out NativePointerState state)
        {
            state = new NativePointerState();
            return _pointer?.Invoke(_context, ref state) > 0;
        }
    }

    public abstract class Component
    {
        public GameObject gameObject { get; internal set; } = null!;
        public Transform transform => gameObject.transform;
        public T? GetComponent<T>() where T : Component => gameObject.GetComponent<T>();
    }

    public sealed class WaitForSeconds
    {
        internal float seconds { get; }

        public WaitForSeconds(float seconds)
        {
            if (!float.IsFinite(seconds) || seconds < 0)
                throw new ArgumentOutOfRangeException(nameof(seconds));

            this.seconds = seconds;
        }
    }

    public sealed class Coroutine
    {
        private readonly Stack<IEnumerator> _stack = new();
        private float _waitSeconds;
        private bool _waitingSeconds;
        private bool _deferFirstAdvance = true;

        internal bool stopped { get; private set; }
        internal bool completed { get; private set; }

        internal Coroutine(IEnumerator routine)
        {
            _stack.Push(
                routine ?? throw new ArgumentNullException(nameof(routine)));

            Resume();
        }

        internal void Stop()
        {
            stopped = true;
            _stack.Clear();
        }

        internal void Advance(float deltaTime)
        {
            if (stopped || completed)
                return;

            if (_deferFirstAdvance)
            {
                _deferFirstAdvance = false;
                return;
            }

            if (_waitingSeconds)
            {
                _waitSeconds -= Math.Max(0, deltaTime);

                if (_waitSeconds > 0)
                    return;

                _waitSeconds = 0;
                _waitingSeconds = false;
            }

            Resume();
        }

        private void Resume()
        {
            while (_stack.Count != 0)
            {
                IEnumerator top = _stack.Peek();

                if (!top.MoveNext())
                {
                    _stack.Pop();
                    continue;
                }

                object? yielded = top.Current;

                if (yielded is IEnumerator nested)
                {
                    _stack.Push(nested);
                    continue;
                }

                if (yielded is WaitForSeconds wait)
                {
                    _waitSeconds = wait.seconds;
                    _waitingSeconds = true;
                }

                return;
            }

            completed = true;
        }
    }

    public abstract class Behaviour : Component
    {
        private readonly List<Coroutine> _coroutines = new();

        public bool enabled { get; set; } = true;

        public Coroutine StartCoroutine(IEnumerator routine)
        {
            var coroutine = new Coroutine(routine);
            _coroutines.Add(coroutine);
            return coroutine;
        }

        public void StopCoroutine(Coroutine coroutine)
        {
            if (coroutine == null) return;
            coroutine.Stop();
        }

        public void StopAllCoroutines()
        {
            foreach (Coroutine coroutine in _coroutines)
                coroutine.Stop();

            _coroutines.Clear();
        }

        internal void AdvanceCoroutines(float deltaTime)
        {
            int count = _coroutines.Count;

            for (int i = 0; i < count && i < _coroutines.Count; ++i)
                _coroutines[i].Advance(deltaTime);

            _coroutines.RemoveAll(
                coroutine => coroutine.stopped || coroutine.completed);
        }
    }

    public sealed class Camera : Component { }
    public sealed class Light : Component { }
    public sealed class MeshRenderer : Component { }
    public sealed class SpriteRenderer : Component { }

    public sealed class GameObject
    {
        private readonly System.Collections.Generic.List<Component> _components = new();
        private string _name = "GameObject";
        private bool _activeSelf = true;
        private ulong _instanceId;
        private bool _nativeBound;

        internal bool nativeBound => _nativeBound;

        public string name
        {
            get
            {
                if (_nativeBound &&
                    NativeWorld.TryGetName(_instanceId, out string current))
                {
                    _name = current;
                }

                return _name;
            }
            set
            {
                string next = value ?? string.Empty;
                _name = next;

                if (_nativeBound &&
                    NativeWorld.available)
                {
                    NativeWorld.SetName(
                        _instanceId,
                        next);
                }
            }
        }

        public bool activeSelf
        {
            get
            {
                if (_nativeBound &&
                    NativeWorld.TryGetActive(_instanceId, out bool current))
                {
                    _activeSelf = current;
                }

                return _activeSelf;
            }
        }

        public ulong instanceId => _instanceId;
        public Transform transform { get; }

        private GameObject(
            bool createNative,
            string requestedName)
        {
            transform = new Transform();
            Attach(transform);

            _name =
                string.IsNullOrEmpty(requestedName)
                    ? "GameObject"
                    : requestedName;

            if (createNative &&
                NativeWorld.available)
            {
                ulong entityId =
                    NativeWorld.Create(
                        _name);

                if (entityId == NativeWorld.InvalidEntity ||
                    !NativeWorld.IsAlive(entityId))
                {
                    throw new InvalidOperationException(
                        "native GameObject creation failed");
                }

                SetNativeState(
                    entityId,
                    _name,
                    true);
            }
        }

        public GameObject()
            : this(true, "GameObject")
        {
        }

        public GameObject(string name)
            : this(true, name)
        {
        }

        internal GameObject(bool createNative)
            : this(createNative, "GameObject")
        {
        }

        public static GameObject? Find(string name)
        {
            if (!NativeWorld.available ||
                string.IsNullOrEmpty(name))
            {
                return null;
            }

            return FromNative(
                NativeWorld.Find(
                    name));
        }

        public static void Destroy(
            GameObject? target)
        {
            if (target == null ||
                !target._nativeBound ||
                !NativeWorld.available)
            {
                return;
            }

            NativeWorld.Destroy(
                target._instanceId);
        }

        public void Destroy() =>
            Destroy(this);

        internal static GameObject? FromNative(ulong entityId)
        {
            if (entityId == NativeWorld.InvalidEntity ||
                !NativeWorld.IsAlive(entityId))
            {
                return null;
            }

            var result = new GameObject(createNative: false);
            string currentName = string.Empty;
            bool currentActive = true;
            NativeWorld.TryGetName(entityId, out currentName);
            NativeWorld.TryGetActive(entityId, out currentActive);
            result.SetNativeState(entityId, currentName, currentActive);
            return result;
        }

        internal void Attach(Component component)
        {
            component.gameObject = this;

            if (!_components.Contains(component))
                _components.Add(component);
        }

        internal void SetNativeState(
            ulong instanceId,
            string name,
            bool active)
        {
            _instanceId = instanceId;
            _name = name ?? string.Empty;
            _activeSelf = active;
            _nativeBound = true;
        }

        public ulong GetInstanceID() => _instanceId;

        public void SetActive(bool active)
        {
            _activeSelf = active;

            if (_nativeBound &&
                NativeWorld.available)
            {
                NativeWorld.SetActive(
                    _instanceId,
                    active);
            }
        }

        public bool HasComponent<T>() where T : Component
        {
            if (_nativeBound &&
                NativeWorld.available)
            {
                string? nativeType =
                    NativeWorld.NativeComponentName(typeof(T));

                if (nativeType != null)
                    return NativeWorld.HasComponent(_instanceId, nativeType);
            }

            foreach (var component in _components)
                if (component is T)
                    return true;

            return false;
        }

        public T? GetComponent<T>() where T : Component
        {
            foreach (var component in _components)
                if (component is T typed)
                    return typed;

            if (!_nativeBound ||
                !NativeWorld.available ||
                typeof(Behaviour).IsAssignableFrom(typeof(T)))
            {
                return null;
            }

            string? nativeType =
                NativeWorld.NativeComponentName(typeof(T));

            if (nativeType == null ||
                !NativeWorld.HasComponent(_instanceId, nativeType))
            {
                return null;
            }

            if (Activator.CreateInstance(typeof(T), nonPublic: true) is not T proxy)
                return null;

            Attach(proxy);
            return proxy;
        }

        public T AddComponent<T>() where T : Component, new()
        {
            var component = new T();
            Attach(component);
            return component;
        }
    }

    public sealed class Transform : Component
    {
        private Vector3 _localPosition;
        private Vector3 _localScale = Vector3.one;
        private Quaternion _localRotation = Quaternion.identity;

        private void RefreshNative()
        {
            if (!gameObject.nativeBound ||
                !NativeWorld.TryGetTransform(
                    gameObject.instanceId,
                    out NativeTransformState state))
            {
                return;
            }

            _localPosition =
                new Vector3(state.px, state.py, state.pz);
            _localRotation =
                new Quaternion(state.rx, state.ry, state.rz, state.rw);
            _localScale =
                new Vector3(state.sx, state.sy, state.sz);
        }

        private void PushNative()
        {
            if (!gameObject.nativeBound ||
                !NativeWorld.available)
            {
                return;
            }

            NativeTransformState state = new NativeTransformState
            {
                px = _localPosition.x,
                py = _localPosition.y,
                pz = _localPosition.z,
                rx = _localRotation.x,
                ry = _localRotation.y,
                rz = _localRotation.z,
                rw = _localRotation.w,
                sx = _localScale.x,
                sy = _localScale.y,
                sz = _localScale.z
            };

            NativeWorld.SetTransform(
                gameObject.instanceId,
                ref state);
        }

        internal void SetNativeState(
            Vector3 position,
            Quaternion rotation,
            Vector3 scale)
        {
            _localPosition = position;
            _localRotation = rotation;
            _localScale = scale;
        }

        internal void GetCachedState(
            out Vector3 position,
            out Quaternion rotation,
            out Vector3 scale)
        {
            position = _localPosition;
            rotation = _localRotation;
            scale = _localScale;
        }

        public Vector3 localPosition
        {
            get
            {
                RefreshNative();
                return _localPosition;
            }
            set
            {
                _localPosition = value;
                PushNative();
            }
        }

        public Vector3 position
        {
            get => localPosition;
            set => localPosition = value;
        }

        public Vector3 localScale
        {
            get
            {
                RefreshNative();
                return _localScale;
            }
            set
            {
                _localScale = value;
                PushNative();
            }
        }

        public Quaternion localRotation
        {
            get
            {
                RefreshNative();
                return _localRotation;
            }
            set
            {
                _localRotation = value;
                PushNative();
            }
        }

        public Transform? parent
        {
            get
            {
                if (!gameObject.nativeBound)
                    return null;

                ulong parentId =
                    NativeWorld.GetParent(
                        gameObject.instanceId);

                return GameObject
                    .FromNative(parentId)?
                    .transform;
            }
            set
            {
                if (!gameObject.nativeBound ||
                    !NativeWorld.available)
                {
                    return;
                }

                ulong parentId =
                    value?.gameObject.instanceId ??
                    NativeWorld.InvalidEntity;

                NativeWorld.SetParent(
                    gameObject.instanceId,
                    parentId);
            }
        }

        public int childCount
        {
            get
            {
                if (!gameObject.nativeBound)
                    return 0;

                return Math.Max(
                    0,
                    NativeWorld.GetChildCount(
                        gameObject.instanceId));
            }
        }

        public Transform GetChild(int index)
        {
            if (index < 0)
                throw new ArgumentOutOfRangeException(nameof(index));

            ulong childId =
                NativeWorld.GetChildAt(
                    gameObject.instanceId,
                    index);

            GameObject? child =
                GameObject.FromNative(childId);

            return child?.transform ??
                throw new ArgumentOutOfRangeException(nameof(index));
        }

        public Vector3 forward => Vector3.forward;
    }

    public enum KeyCode : uint
    {
        None = 0,
        A = 1, B = 2, C = 3, D = 4, E = 5, F = 6, G = 7,
        H = 8, I = 9, J = 10, K = 11, L = 12, M = 13,
        N = 14, O = 15, P = 16, Q = 17, R = 18, S = 19,
        T = 20, U = 21, V = 22, W = 23, X = 24, Y = 25, Z = 26,
        Alpha0 = 27, Alpha1 = 28, Alpha2 = 29, Alpha3 = 30, Alpha4 = 31,
        Alpha5 = 32, Alpha6 = 33, Alpha7 = 34, Alpha8 = 35, Alpha9 = 36,
        Space = 37,
        Return = 38,
        Escape = 39,
        Tab = 40,
        Backspace = 41,
        UpArrow = 42,
        DownArrow = 43,
        LeftArrow = 44,
        RightArrow = 45,
        LeftShift = 46,
        RightShift = 47,
        LeftControl = 48,
        RightControl = 49,
        LeftAlt = 50,
        RightAlt = 51,
        Mouse0 = 52,
        Mouse1 = 53,
        Mouse2 = 54
    }

    public readonly struct Vector2
    {
        public readonly float x;
        public readonly float y;

        public Vector2(float x, float y)
        {
            this.x = x;
            this.y = y;
        }

        public static Vector2 zero =>
            new Vector2(0, 0);

        public static Vector2 operator +(Vector2 a, Vector2 b) =>
            new Vector2(a.x + b.x, a.y + b.y);

        public static Vector2 operator *(Vector2 a, float b) =>
            new Vector2(a.x * b, a.y * b);
    }

    public static class Input
    {
        public static bool GetKey(KeyCode key) =>
            NativeInput.GetKey((uint)key);

        public static bool GetKeyDown(KeyCode key) =>
            NativeInput.GetKeyDown((uint)key);

        public static bool GetKeyUp(KeyCode key) =>
            NativeInput.GetKeyUp((uint)key);

        private static NativePointerState Pointer
        {
            get
            {
                NativeInput.TryGetPointer(
                    out NativePointerState state);
                return state;
            }
        }

        public static Vector2 mousePosition
        {
            get
            {
                NativePointerState state = Pointer;
                return new Vector2(state.x, state.y);
            }
        }

        public static Vector2 mouseDelta
        {
            get
            {
                NativePointerState state = Pointer;
                return new Vector2(state.deltaX, state.deltaY);
            }
        }

        public static Vector2 mouseScrollDelta
        {
            get
            {
                NativePointerState state = Pointer;
                return new Vector2(0, state.wheelY);
            }
        }
    }

    public readonly struct Vector3
    {
        public readonly float x;
        public readonly float y;
        public readonly float z;

        public Vector3(float x, float y, float z)
        {
            this.x = x; this.y = y; this.z = z;
        }

        public static Vector3 zero => new Vector3(0, 0, 0);
        public static Vector3 one => new Vector3(1, 1, 1);
        public static Vector3 forward => new Vector3(0, 0, 1);

        public static Vector3 operator +(Vector3 a, Vector3 b) =>
            new Vector3(a.x + b.x, a.y + b.y, a.z + b.z);

        public static Vector3 operator *(Vector3 a, float b) =>
            new Vector3(a.x * b, a.y * b, a.z * b);
    }

    public readonly struct Quaternion
    {
        public readonly float x;
        public readonly float y;
        public readonly float z;
        public readonly float w;

        public Quaternion(float x, float y, float z, float w)
        {
            this.x = x; this.y = y; this.z = z; this.w = w;
        }

        public static Quaternion identity => new Quaternion(0, 0, 0, 1);
    }

    public static class Time
    {
        public static float deltaTime { get; private set; } = 0.0166667f;
        public static float fixedDeltaTime { get; internal set; } = 0.02f;
        public static float time { get; private set; }
        public static ulong frameCount { get; private set; }

        internal static void SetDeltaTime(float value)
        {
            deltaTime =
                value >= 0 && float.IsFinite(value)
                    ? value
                    : 0;

            time += deltaTime;
            frameCount++;
        }

        internal static void Reset()
        {
            deltaTime = 0.0166667f;
            time = 0;
            frameCount = 0;
        }
    }

    public static class Debug
    {
        public static void Log(object? message) { }
        public static void LogWarning(object? message) { }
        public static void LogError(object? message) { }
    }
}
)CS";

    return source.str();
}

} // namespace

bool ManagedProjectGenerator::generate(
    const ManagedProjectConfig& config,
    ManagedProjectOutput& output,
    std::string* error) {

    if (config.project_root.empty() ||
        config.project_name.empty() ||
        config.target_framework.empty() ||
        config.runtime_framework_version.empty()) {
        set_error(
            error,
            "managed project requires project root and name");
        return false;
    }

    const auto generated_directory =
        config.project_root /
        ".nengine" /
        "Managed";

    std::error_code ec;
    std::filesystem::create_directories(
        generated_directory,
        ec);

    if (ec) {
        set_error(
            error,
            "could not create managed generation directory");
        return false;
    }

    output.project_path =
        generated_directory /
        (config.project_name + ".csproj");

    output.api_project_path =
        generated_directory /
        "NEngine.API.csproj";

    output.api_stub_path =
        generated_directory /
        "NEngine.API.cs";

    output.bridge_project_path =
        generated_directory /
        "NEngine.Bridge.csproj";

    output.bridge_path =
        generated_directory /
        "NEngine.ManagedBridge.cs";

    output.runtime_config_path =
        generated_directory /
        (config.project_name +
         ".runtimeconfig.json");

    output.solution_path =
        config.project_root /
        (config.project_name + ".sln");

    std::ostringstream project;

    project
        << "<Project Sdk=\"Microsoft.NET.Sdk\">\n"
        << "  <PropertyGroup>\n"
        << "    <TargetFramework>"
        << xml_escape(
            config.target_framework)
        << "</TargetFramework>\n"
        << "    <LangVersion>latest</LangVersion>\n"
        << "    <Nullable>enable</Nullable>\n"
        << "    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>\n"
        << "    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>\n"
        << "    <AssemblyName>"
        << xml_escape(config.project_name)
        << "</AssemblyName>\n"
        << "  </PropertyGroup>\n"
        << "  <ItemGroup>\n"
        << "    <Compile Include=\"../../Assets/Scripts/**/*.cs\" />\n"
        << "  </ItemGroup>\n"
        << "  <ItemGroup>\n"
        << "    <ProjectReference Include=\"NEngine.API.csproj\" />\n"
        << "    <ProjectReference Include=\"NEngine.Bridge.csproj\" ReferenceOutputAssembly=\"false\" />\n"
        << "  </ItemGroup>\n";

    std::ostringstream api_project;

    api_project
        << "<Project Sdk=\"Microsoft.NET.Sdk\">\n"
        << "  <PropertyGroup>\n"
        << "    <TargetFramework>"
        << xml_escape(
            config.target_framework)
        << "</TargetFramework>\n"
        << "    <LangVersion>latest</LangVersion>\n"
        << "    <Nullable>enable</Nullable>\n"
        << "    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>\n"
        << "    <AssemblyName>NEngine.API</AssemblyName>\n"
        << "  </PropertyGroup>\n"
        << "  <ItemGroup>\n"
        << "    <Compile Include=\"NEngine.API.cs\" />\n"
        << "  </ItemGroup>\n"
        << "</Project>\n";

    std::ostringstream bridge_project;

    bridge_project
        << "<Project Sdk=\"Microsoft.NET.Sdk\">\n"
        << "  <PropertyGroup>\n"
        << "    <TargetFramework>"
        << xml_escape(
            config.target_framework)
        << "</TargetFramework>\n"
        << "    <LangVersion>latest</LangVersion>\n"
        << "    <Nullable>enable</Nullable>\n"
        << "    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>\n"
        << "    <AssemblyName>NEngine.Bridge</AssemblyName>\n"
        << "  </PropertyGroup>\n"
        << "  <ItemGroup>\n"
        << "    <Compile Include=\"NEngine.ManagedBridge.cs\" />\n"
        << "    <ProjectReference Include=\"NEngine.API.csproj\" />\n"
        << "  </ItemGroup>\n"
        << "</Project>\n";

    if (!config.packages.empty()) {
        project << "  <ItemGroup>\n";

        for (const auto& package :
             config.packages) {

            if (package.id.empty() ||
                package.version.empty()) {
                continue;
            }

            project
                << "    <PackageReference Include=\""
                << xml_escape(package.id)
                << "\" Version=\""
                << xml_escape(package.version)
                << "\" />\n";
        }

        project << "  </ItemGroup>\n";
    }

    project << "</Project>\n";

    constexpr std::string_view project_guid =
        "{A5DFE48B-DBA9-4B57-A5D2-E8FBA5903B35}";

    constexpr std::string_view api_project_guid =
        "{4E1A67CE-8C2A-4BC0-9813-9A62154E9B43}";

    constexpr std::string_view bridge_project_guid =
        "{C731B50F-76D6-4A42-9E1D-24F40C28AA2E}";

    std::ostringstream solution;

    solution
        << "Microsoft Visual Studio Solution File, Format Version 12.00\r\n"
        << "# Visual Studio Version 17\r\n"
        << "VisualStudioVersion = 17.0.31903.59\r\n"
        << "MinimumVisualStudioVersion = 10.0.40219.1\r\n"
        << "Project(\"{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}\") = \""
        << config.project_name
        << "\", \".nengine\\Managed\\"
        << config.project_name
        << ".csproj\", \""
        << project_guid
        << "\"\r\n"
        << "EndProject\r\n"
        << "Project(\"{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}\") = \"NEngine.API\", \".nengine\\Managed\\NEngine.API.csproj\", \""
        << api_project_guid
        << "\"\r\n"
        << "EndProject\r\n"
        << "Project(\"{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}\") = \"NEngine.Bridge\", \".nengine\\Managed\\NEngine.Bridge.csproj\", \""
        << bridge_project_guid
        << "\"\r\n"
        << "EndProject\r\n"
        << "Global\r\n"
        << "\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\r\n"
        << "\t\tDebug|Any CPU = Debug|Any CPU\r\n"
        << "\t\tRelease|Any CPU = Release|Any CPU\r\n"
        << "\tEndGlobalSection\r\n"
        << "\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\r\n"
        << "\t\t" << project_guid << ".Debug|Any CPU.ActiveCfg = Debug|Any CPU\r\n"
        << "\t\t" << project_guid << ".Debug|Any CPU.Build.0 = Debug|Any CPU\r\n"
        << "\t\t" << project_guid << ".Release|Any CPU.ActiveCfg = Release|Any CPU\r\n"
        << "\t\t" << project_guid << ".Release|Any CPU.Build.0 = Release|Any CPU\r\n"
        << "\t\t" << api_project_guid << ".Debug|Any CPU.ActiveCfg = Debug|Any CPU\r\n"
        << "\t\t" << api_project_guid << ".Debug|Any CPU.Build.0 = Debug|Any CPU\r\n"
        << "\t\t" << api_project_guid << ".Release|Any CPU.ActiveCfg = Release|Any CPU\r\n"
        << "\t\t" << api_project_guid << ".Release|Any CPU.Build.0 = Release|Any CPU\r\n"
        << "\t\t" << bridge_project_guid << ".Debug|Any CPU.ActiveCfg = Debug|Any CPU\r\n"
        << "\t\t" << bridge_project_guid << ".Debug|Any CPU.Build.0 = Debug|Any CPU\r\n"
        << "\t\t" << bridge_project_guid << ".Release|Any CPU.ActiveCfg = Release|Any CPU\r\n"
        << "\t\t" << bridge_project_guid << ".Release|Any CPU.Build.0 = Release|Any CPU\r\n"
        << "\tEndGlobalSection\r\n"
        << "EndGlobal\r\n";

    if (!write_text(
            output.api_stub_path,
            api_stub(
                "NEngine.Bridge"),
            error)) {
        return false;
    }

    if (!write_text(
            output.bridge_path,
            managed_bridge(),
            error)) {
        return false;
    }

    DotnetRuntimeConfig runtime_config;
    runtime_config.target_framework =
        config.target_framework;
    runtime_config.framework_version =
        config.runtime_framework_version;

    if (!write_dotnet_runtime_config(
            output.runtime_config_path,
            runtime_config,
            error)) {
        return false;
    }

    if (!write_text(
            output.api_project_path,
            api_project.str(),
            error)) {
        return false;
    }

    if (!write_text(
            output.bridge_project_path,
            bridge_project.str(),
            error)) {
        return false;
    }

    if (!write_text(
            output.project_path,
            project.str(),
            error)) {
        return false;
    }

    if (!write_text(
            output.solution_path,
            solution.str(),
            error)) {
        return false;
    }

    return true;
}

std::vector<NuGetPackageReference>
ManagedProjectGenerator::load_package_manifest(
    const std::filesystem::path& path,
    std::string* error) {

    std::vector<NuGetPackageReference> result;

    std::ifstream input(
        path,
        std::ios::binary);

    if (!input) {
        return result;
    }

    std::string id;
    std::string version;

    while (input >> id >> version) {
        if (!id.empty() &&
            id.front() == '#') {

            std::string ignored;
            std::getline(input, ignored);
            continue;
        }

        if (id.empty() ||
            version.empty()) {
            continue;
        }

        result.push_back({
            std::move(id),
            std::move(version)
        });
    }

    if (!input.eof() && input.fail()) {
        set_error(
            error,
            "managed package manifest parse failed");
    }

    return result;
}

} // namespace nengine::scripting
